# Generated by Django 2.1.5 on 2021-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipy_fotbal',
            name='tipy_skore_sk',
            field=models.CharField(max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='tipy_fotbal',
            name='tipy_skore_v',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
