# Generated by Django 2.1.5 on 2021-05-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0002_auto_20210531_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipy_fotbal',
            name='tipy_skore_sk',
            field=models.CharField(max_length=108, null=True),
        ),
    ]
