# Generated by Django 2.1.5 on 2021-06-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0003_auto_20210531_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipy_fotbal',
            name='tipy_skore_sk',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
