# Generated by Django 2.1.5 on 2021-06-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0004_auto_20210601_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipy_fotbal',
            name='tipy_skupina',
        ),
        migrations.RemoveField(
            model_name='tipy_fotbal',
            name='tipy_vyraz',
        ),
    ]
