# Generated by Django 2.1.5 on 2021-06-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0006_komenty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komenty',
            options={'verbose_name': 'komentář', 'verbose_name_plural': 'komentáře'},
        ),
    ]
