# Generated by Django 2.1.5 on 2021-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0007_auto_20210601_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komenty',
            name='id',
        ),
        migrations.AlterField(
            model_name='komenty',
            name='koment',
            field=models.TextField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
