# Generated by Django 2.1.5 on 2021-06-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0008_auto_20210601_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komenty',
            name='jmeno',
        ),
        migrations.DeleteModel(
            name='Komenty',
        ),
    ]
