# Generated by Django 2.1.5 on 2021-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotbal', '0009_auto_20210601_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komenty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('koment', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'komentář',
                'verbose_name_plural': 'komentáře',
            },
        ),
    ]
